GPU: 3
b1: 0.5
b2: 0.999
batch_size: 1
datasets_folder: 20201020_10_ZOOM1.3_550Vx575H_FOV_30Hz_170umdepth_soma_10AMP_0.3_0001
datasets_path: datasets
epoch: 0
gap_h: 64
gap_s: 150
gap_w: 64
img_h: 64
img_s: 464
img_w: 64
lr: 5.0e-05
n_epochs: 20
normalize_factor: 1
output_dir: ./results
train_datasets_size: 1200
