GPU: 0
b1: 0.5
b2: 0.999
batch_size: 1
datasets_folder: DataForPytorch
datasets_path: datasets
epoch: 0
gap_h: 60
gap_s: 60
gap_w: 60
img_h: 150
img_s: 150
img_w: 150
lr: 5.0e-05
n_epochs: 20
normalize_factor: 1
output_dir: ./results
train_datasets_size: 1200
